### ISSUE TITLE
wonderful with ts files but breaks w/ tsx files

### ISSUE THREAD

**Issue by iambumblehead** [pahen/detective-typescript#2]
thank you for this excellent tool :)

I've been using this with a typescript application and today I added a tsx file and found that detective-typescript throws an error which looks like this,

```
{ index: 727,
  lineNumber: 48,
  column: 14,
  message: '\'>\' expected.' }
```
what is the best way to resolve this? will you publish this module to npm?

**Comment by pahen** [comment]
This module is not ready for use yet. Will let you know when/if I'll publish it to NPM.

**Comment by fatso83** [comment]
Any updates on this? We had to disable use of dependency-checker in 2019 due to this, but was hoping there were some updates.
