### ISSUE TITLE
Adding a `filename` option that would auto-enable TSX on the right extension

### ISSUE THREAD

**Issue by fatso83** [pahen/detective-typescript#32]
Ref https://github.com/dependency-check-team/dependency-check/issues/112#issuecomment-568456236 I was wondering if could add support for a `options.filename` option here, which in this module, would auto-enable `jsx:true` if the extension of said filename was `.tsx`.

**Comment by pahen** [comment]
You should use `detective.tsx()` when reading TSX files instead. See https://github.com/pahen/detective-typescript#usage-with-tsx

**Comment by fatso83** [comment]
That won't work, unfortunately, as the linked thread would show, as `dependency-check` adds detectives at run time and feeds them the same same arguments, using the same API. I could work around this by creating a new package called `typescript-tsx`, of course, that basically just wraps `detective.tsx()`, but that seemed a bit weird :)

**Comment by pahen** [comment]
Then I would rather add support for passing in option `jsx:true` to `detective()` that will do the same as `detective.tsx()`

**Comment by pahen** [comment]
You can actually use "jsx:true" as option already. Added note in README about it now. See https://github.com/pahen/detective-typescript/tree/master/#options

**Comment by pahen** [comment]
So no need to create another module

**Comment by fatso83** [comment]
[Already had published and fixed the issue by the time you replied](https://github.com/dependency-check-team/dependency-check/issues/112#issuecomment-768251307) :smile_cat:  Took me a full 5 minutes to solve this 2 year issue with that approach, instead of trying to change lots of other people's packages, so that seemed like the most pragmatic approach.

**Comment by pahen** [comment]
👍
