### ISSUE TITLE
Release v11.2.0 with typescript 5.1 support

### ISSUE THREAD

**Issue by legobeat** [pahen/detective-typescript#55]
Would be sweet to get a published release with cb1c37c03db3f36f8f25d5ea01f5cc3da62d72f6 <3

@XhmikosR

**Comment by XhmikosR** [comment]
@legobeat typescript is using the caret operator so it doesn't really need a new release.

Unsure when I'll find some time to update the deps and cut new releases for dependent packages.

**Comment by XhmikosR** [comment]
@legobeat I made #60 but there's a test failure and I'm unsure why this happens. Any help is welcome!

**Comment by XhmikosR** [comment]
Released https://github.com/dependents/detective-typescript/releases/tag/v11.2.0
